name: tv_focus
description: "A project for work with focus"
version: 0.0.10

environment:
  sdk: ">=3.3.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
